# Generated by Django 4.2.6 on 2023-10-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customgroup'),
        ),
    ]
