# Generated by Django 4.2.6 on 2023-10-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_user_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_join',
            new_name='date_joined',
        ),
    ]
