# Generated by Django 4.2.6 on 2023-10-25 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_date_join_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
